### ISSUE TITLE
Push update to NPM

### ISSUE THREAD

**Issue by jazoom** [buefy/nuxt-buefy#10]
Is it coming time to push the latest to NPM? This bug is causing issues, and it has already been fixed in the latest version, which `nuxt-buefy` has already pinned to.

https://github.com/buefy/buefy/issues/814

**Comment by anteriovieira** [comment]
Hi @jazoom , try installing nuxt-buefy version `v0.0.5`.

**Comment by jazoom** [comment]
Awesome. Thanks for pushing the update to NPM.
