### ISSUE TITLE
Unable to build Nuxt due to an error with PostCSS

### ISSUE THREAD

**Issue by agm1984** [buefy/nuxt-buefy#103]
This morning we encountered a build failure since adding nuxt-buefy to our project. Everything worked fine via `npm run dev`, but when we did `npm run build`, there was a very ambiguous error.

We found a solution for it, so I will link it here. I posted the project config there for analysis if desired:
https://stackoverflow.com/a/67827344/6141025

**Comment by pencilcheck** [comment]
the stackoverflow solution didn't work for me.

**Comment by satezmedia** [comment]
Hey, I managed to fix it by installing 
`npm install postcss-custom-properties --save-dev`

**Comment by wesdevpro** [comment]
This issue seems stale so I have closed it  :)
