### ISSUE TITLE
bulma and prism not playing well - how to adjust which bulma files are pulled in by buefy

### ISSUE THREAD

**Issue by tansaku** [buefy/nuxt-buefy#107]
I'm having the problem described here https://github.com/koca/vue-prism-editor/issues/93 where prism and bulma are not playing nicely.  The solution should be to pull in a subset of bulma files, but how can I do that in the context of nuxt-buefy?

**Comment by mitya33** [comment]
I'd be interested to know the answer to this. Buefy seems to lack a mechanism to control which Bulma modules are loaded. You can do this manually, of course, but it would be good if there were a way to specify them, for example, via an entry in the Nuxt config.

**Comment by tansaku** [comment]
thanks @mitya33 - pardon my ignorance but could you describe the manual process?  At the moment I'm overiding styles in the vue page itself to work around this

**Comment by wesdevpro** [comment]
https://github.com/koca/vue-prism-editor/issues/93
