### ISSUE TITLE
Wrong dependency for nuxt-buefy@^0.4.16 ?

### ISSUE THREAD

**Issue by yangwao** [buefy/nuxt-buefy#114]
Hey, I've just noticed you pushed https://github.com/buefy/nuxt-buefy/blob/master/package.json#L33

But that package isn't up or being finished?

`error Couldn't find any versions for "buefy" that matches "^0.9.15"`

![image](https://user-images.githubusercontent.com/5887929/154242865-9775cae5-b007-4ef4-92bc-f973e076e513.png)

### Ref
- https://github.com/kodadot/nft-gallery/pull/2364

**Comment by jtommy** [comment]
@yangwao  Just published, I apologize for the inconvenience 😞

**Comment by yangwao** [comment]
No worries, you are doing great job for VueJS ecosystem ;) 
<img src="https://media1.giphy.com/media/xUA7b0Klw8Wfor7FWo/giphy.gif"/>
