### ISSUE TITLE
Buefy version is wrong in the last Nuxt-Buefy module

### ISSUE THREAD

**Issue by miroslavgeorgiev** [buefy/nuxt-buefy#117]
In the last commit https://github.com/buefy/nuxt-buefy/commit/e2d051c9228a90658f76b55b83d0ddb24d311837 the `Buefy` dep verions is wrong - `0.9.10` instead of `0.9.19`.

Btw can you sync the versions name of both somehow - I mean when we have `Buefy v0.9.19` to have `Nuxt-Buefy v0.9.19` again?
I checked that here https://github.com/buefy/nuxt-buefy/commit/9f0eacfa712ccd9a7df0023d33ac9a4fa9befa0d you've forgotten to increase the Buefy dep version and from that on we have difference in version numbering.
Now when fix this issue we'll have another difference - probably you should make `Nuxt-Buefy v.0.4.20.1` and go this way until you hit `Buefy v0.9.21` and then continue to `Nuxt-Buefy v.0.4.21`?

**Comment by jtommy** [comment]
You are right, can you make a PR?

**Comment by jtommy** [comment]
Just released, thanks and I apologize for the inconvenience 😞

**Comment by miroslavgeorgiev** [comment]
You're doing great stuff, so no worries, mate!
I know what is to work on multiple stuff and update in rush when trying to resolve all you can, so we're just humans :)
