### ISSUE TITLE
Using buefy as peer dependencies instead of dependencies

### ISSUE THREAD

**Issue by kieusonlam** [buefy/nuxt-buefy#12]
If using buefy as peer dependecies, people can control their own buefy version, they don't this to wait for `nuxt-buefy` to update buefy version. What do you think?

**Comment by damien-biasotto** [comment]
That's a good idea and had been discussed in a previous PR : https://github.com/buefy/nuxt-buefy/pull/8#issuecomment-395807663 .

Previously, the choice had been made to fix the version of buefy to ensure compatiblity between buefy and nuxt.
