### ISSUE TITLE
nuxt-buefy template switching from mobile to desktop view

### ISSUE THREAD

**Issue by giovannilaperna** [buefy/nuxt-buefy#120]
I have this [codesandbox ](https://codesandbox.io/s/nuxt-buefy-mobile-hp8gii) with a very basic nuxt and nuxt-buefy template.

If you open the preview in a new window and you switch in the chrome devtools to mobile view, you will see that the page is rendered as mobile for a few seconds but then it switches to desktop view.

The same happens locally and deployed with `nuxt generate` on netlify.

You can view it in action [here](https://csb-hp8gii.netlify.app/)

What can be the issue?

Here is the video of what I described: https://youtu.be/1oa_SYpmBbE

**Comment by giovannilaperna** [comment]
Forcing these values in my `style.scss` file does not fix the issue:

```
$tablet: 769px;
$desktop: 960px;
$widescreen: 1152px;
$fullhd: 1344px;
```

**Comment by giovannilaperna** [comment]
On firefox, if you disable touch simulation, it display correctly (mobile) if you re-enable it, it display as desktop.

See it here: https://youtube.com/shorts/9glx3jp8clQ

**Comment by giovannilaperna** [comment]
@jtommy Can you maybe help me? I'm stuck with two projects ready for production due to this.

**Comment by jtommy** [comment]
Ad discussed on Discord, it's missing meta tag
