### ISSUE TITLE
Circle CI Build Failure

### ISSUE THREAD

**Issue by wesdevpro** [buefy/nuxt-buefy#136]
### The Error
```
error teeny-request@7.1.1: The engine "node" is incompatible with this module. Expected version ">=10".
error An unexpected error occurred: "Found incompatible module".
```

teeny-request@7.1.1 is a dependency used by codecov@3.1.0 

Does anyone know what this dependency is used for?

**Comment by gmercey** [comment]
I cannot reproduce the issue on my local machine but I guess we could bump the engine node version to 10 or higher?

https://github.com/buefy/nuxt-buefy/blob/923ce8fdd804c828951f22a82f407091a62f57b8/package.json#L45-L47

**Comment by wesdevpro** [comment]
I'm not sure if you will be able to reproduce this on your local. 
![image](https://github.com/buefy/nuxt-buefy/assets/11604664/9c0f87ba-8218-4abd-a6d4-cac08060af52)
I get this error from CircleCI. I'll have to do some more digging when I have some more time later before we bump node versions.
