### ISSUE TITLE
how to add buefy constructor options ?

### ISSUE THREAD

**Issue by paolog22** [buefy/nuxt-buefy#14]
how to i add this 

> https://buefy.github.io/#/documentation/constructor-options

do i need to create a plugin ?

thank you

**Comment by anteriovieira** [comment]
Hi @paolog22 try https://github.com/buefy/nuxt-buefy#usage

**Comment by paolog22** [comment]
@anteriovieira thanks

**Comment by vimm0** [comment]
```javascript
{
    modules: [
        ['nuxt-buefy', { css: false, materialDesignIcons: false }],
    ]
}
``` 
Ref: Bulma [start docs](https://buefy.github.io/#/documentation/start)
