### ISSUE TITLE
Ala-carte Style [picked component only]

### ISSUE THREAD

**Issue by paolog22** [buefy/nuxt-buefy#17]
how to import only component need ?
i am only using 3 component of bulma show to import only that 3 component like `b-input` to minimize my vendor ..
thank you

**Comment by anteriovieira** [comment]
Hi @paolog22 , we do not have this feature implemented, but a pull request is welcome.

**Comment by jtommy** [comment]
@paolog22 We're working on it https://github.com/buefy/buefy/pull/826 and we think it be ready in the next release

**Comment by paolog22** [comment]
thanks looking forward to it :) hooray!
