### ISSUE TITLE
Tabs are not SSR

### ISSUE THREAD

**Issue by mydesireiscoma** [buefy/nuxt-buefy#18]
### What I did
- `npm i nuxt-buefy`
- Add module to `nuxt.config.js`
```js
module.exports = {
  // ...
  modules: [
    'nuxt-buefy'
  ]
  // ...
}
```
- Copied code from official Buefy Tabs example
```html
<b-tabs>
  <b-tab-item label="Pictures" icon="google-photos"></b-tab-item>
  <b-tab-item label="Music" icon="library-music"></b-tab-item>
  <b-tab-item label="Videos" icon="video"></b-tab-item>
</b-tabs>
```

### What I expected
- Everything I need is rendered on the server side

### What I got
- Tabs are not rendered on the server side

**Comment by anteriovieira** [comment]
Hi @mydesireiscoma , please, see if there is no other modules property in your configuration file.

**Comment by RTK99** [comment]
@anterioviera can confirm that this is a major issue.

**Comment by duythang** [comment]
I met issue too
```javascript
error ReferenceError: File is not defined
```

**Comment by jtommy** [comment]
@duythang  https://github.com/buefy/nuxt-buefy/issues/32 but it's no related to this issue

**Comment by RTK99** [comment]
any update on this issue? I really need my tabs.

**Comment by jtommy** [comment]
@RTK99 Can you provide us your config and tabs code ? Are you using 0.3.2 version (0.7.1 Buefy) ?

**Comment by GreenmeisterDavid** [comment]
I still have this issue (see also #478), any update on a possible fix?
