### ISSUE TITLE
document is not defined error

### ISSUE THREAD

**Issue by konojunya** [buefy/nuxt-buefy#19]
When using `this.$toast.open` in Nuxt's project, there is no document on the server, so an error is generated.

**Comment by anteriovieira** [comment]
Hi @konojunya , I did not quite understand, could you give us an example and the error generated?

**Comment by konojunya** [comment]
@anteriovieira

Sorry, I forgot to put sample code.

This is minimal example.

```js
export default {
  async created() {
    try {
      await this.$store.dispatch(GET_SOME);
    } catch(err) {
      this.$toast.open("hogehoge error!");
    }
  }
}
```

Just slip the life cycle to `mounted`, so you can refer to the `document` so you will not get an error.

**Comment by anteriovieira** [comment]
@konojunya , sorry, I do not see how this error could be associated with nuxt-buefy.

**Comment by Aposhian** [comment]
It seems that this is because nuxt-buefy relies on browser specific code (such as `document` being defined. If nuxt is running in universal mode then the created hook is run [client-side AND server-side](https://github.com/nuxt/nuxt.js/issues/5253). This package should really document this behavior if it is meant to plug-and-play with nuxt.

**Comment by jtommy** [comment]
@Aposhian what do you mean?

**Comment by Aposhian** [comment]
You can read about the different operating modes of next here. In universal mode, some of the code can run server-side, client-side, or on both. This [post](https://tech.onestopbeauty.online/front-end/understanding-nuxt-vue-hooks-and-lifecycle-part1/) does a good job of explaining which Vue lifecycle hooks are run where. Some global variables like `window` or `document` are only defined when that code is run client-side, in the browser. If you try to use them in code that runs on the server at some point, it will break, as described [here](https://nuxtjs.org/faq/window-document-undefined/). One way to address that is to check the special environment variables `process.client` or `process.server`.
```js
if (process.client) {
  // do browser-specific stuff
  console.log(window.location) // this is defined
}
```

**Comment by jtommy** [comment]
Ok but Buefy check window object, what's the issue ?
