### ISSUE TITLE
advantage of using as module??

### ISSUE THREAD

**Issue by nikugogoi** [buefy/nuxt-buefy#20]
can we use the buefy methods from the context or context.app (https://nuxtjs.org/api/context) because thats something that looks like what the module is used for

**Comment by anteriovieira** [comment]
Hi @nikugogoi , the methods are already available in the instance of the vue.

https://github.com/buefy/buefy/blob/86f10bc5a7f99acb32a2c3a38c666fdb69bb9be2/src/utils/plugins.js#L12-L14
