### ISSUE TITLE
[Bug] Cannot resolve "buefy/lib/buefy.css"

### ISSUE THREAD

**Issue by mikejavier** [buefy/nuxt-buefy#23]
I try to create a new NuxtJS app using `nuxt-create-app` but add nuxt-buefy module bug breaks in console.

![image](https://user-images.githubusercontent.com/5166571/45190181-f0912680-b212-11e8-8084-66d737a1e94d.png)

I believe that the problem is because the path `buefy/lib/buefy.css` does not exist
the correct one would be `buefy/dist/buefy.css`

https://github.com/buefy/nuxt-buefy/blob/9d5c314ab3e6d4aa6917a9748676050056495c2f/lib/module.js#L23

**Comment by mikejavier** [comment]
Doing some more testing the bug only happens when you install nuxt-buefy by create-nuxt-app CLI.
The problem is that in the package.json is being indicated to install the version 0.0.4 that in fact would have to be 0.2.0.

https://github.com/nuxt-community/create-nuxt-app/blob/master/template/_package.json#L44

**Comment by jtommy** [comment]
@mikejavier Folder issue is fixed

**Comment by akdasa** [comment]
Looks like it requires 0.6.7 (it's not working with 0.6.6 for me).

**Comment by mikejavier** [comment]
@jtommy the change of folder name happened in version 0.6.7 of buefy, nuxt-buefy is installing version 0.6.6 

https://unpkg.com/nuxt-buefy@0.1.1/package.json

The version of the module that was in 0.2.0 was to 0.1.1 would not be interesting to be 0.2.1?

**Comment by jtommy** [comment]
0.6.7 has a new structure

**Comment by jtommy** [comment]
@mikejavier You're right. I didn't change package.json

**Comment by anteriovieira** [comment]
Release ``v0.2.1`

**Comment by jtommy** [comment]
@mikejavier You might update your PR, thanks!

**Comment by mikejavier** [comment]
thank you @jtommy and @anteriovieira.

I'll update the PR

**Comment by mikejavier** [comment]
PR updated, now all you have to do is wait for the `create-nuxt-app` personnel to accept, I believe that we can close this issue.

**Comment by Noxiess** [comment]
no
