### ISSUE TITLE
Tree shaking ?

### ISSUE THREAD

**Issue by asafyish** [buefy/nuxt-buefy#29]
Hi,

I am using this library in a freshly created nuxt 2 project, and I can see buefy.js takes a large portion of the bundle size, is that intentional ?

<img width="1437" alt="screen shot 2018-10-06 at 10 00 34 pm" src="https://user-images.githubusercontent.com/1331750/46574906-d5513c80-c9b3-11e8-9dd1-1aebcce86767.png">

**Comment by anteriovieira** [comment]
Hi @asafyish ,

Thanks for using Buefy in your projects.

Could you forward this message to [buefy/buefy](https://github.com/buefy/buefy) repository? Thanks.

**Comment by asafyish** [comment]
Ok thanks.
