### ISSUE TITLE
this.$toast is undefined

### ISSUE THREAD

**Issue by StevenAvelino24** [buefy/nuxt-buefy#31]
Hello,

I'm trying to open a Toast and I get the error 'Uncaught TypeError: Cannot read property 'open' of undefined'.

Is it a known issue or do I have to create a plugin to add the Buefy component to Vue ?

Thanks in advance

**Comment by anteriovieira** [comment]
Hi @StevenAvelino24 , this problem it's not related to Buefy.

You can install the [@nuxtjs/toast](https://github.com/nuxt-community/modules/tree/master/packages/toast) package to fix the problem.
