### ISSUE TITLE
Latest version (0.3.1) is broken

### ISSUE THREAD

**Issue by zhyupe** [buefy/nuxt-buefy#32]
Buefy 0.7.0 introduced a breaking error for SSR in Upload component (buefy/buefy#1024). Therefore, all newly created projects will fail in building (see [CI logs](https://circleci.com/gh/buefy/nuxt-buefy/37)).

Please take down the latest version until they release the fix.

**Comment by jtommy** [comment]
@zhyupe ,  the fix will be available in the next version (`v0.7.1`).  But as workaround add this line to your file nuxt.config.js

```js
// nuxt.config.js

global.File= typeof window === 'undefined' ? Object : window.File

...
```

**Comment by rikoz** [comment]
please fix this bug

**Comment by jtommy** [comment]
It's fixed but we have to release new version but above there is a workaround

**Comment by jtommy** [comment]
https://github.com/buefy/nuxt-buefy/commit/2fb856f9609036d34cdde8d97b2723a3ad38800a
