### ISSUE TITLE
Customize typography helpers

### ISSUE THREAD

**Issue by markusbroman** [buefy/nuxt-buefy#33]
Hi,

I'm trying to customize typography helpers for my project. E.g classes like is-size-1 and is-size-1-mobile.

I have managed to make other customizations, like primary colors and such. But I just cant customize the sizes-variables. Is this possible?

Thanks!

**Comment by jtommy** [comment]
@markusbroman It's a bulma question https://bulma.io/documentation/modifiers/typography-helpers/
