### ISSUE TITLE
Can't use dialog

### ISSUE THREAD

**Issue by pontakornth** [buefy/nuxt-buefy#37]
## What did I do?

use this.$dialog.open("some message") and import Dialog and use same method

## What happened?

Error said "_vm.alert is not a function"

## What do I expect to happen?

A normal dialog appear.

## Can you provide system details?

OS: Windows 10
Nuxt-buefy: 0.3.2

**Comment by pontakornth** [comment]
I was wrong sorry.

**Comment by kissu** [comment]
@pontakornth mind giving more details?
