### ISSUE TITLE
Error running with Nuxt

### ISSUE THREAD

**Issue by ais-one** [buefy/nuxt-buefy#4]
Tested on:

- create-nuxt-app
- nuxt v1.0 & v1.4
- nuxt-buefy v0.0.4

Error Shows HTMLElement is not defined

It could be a problem with buefy, 0.6.4 seems not to like playing with nuxt at all.

is it related to this?

https://github.com/buefy/buefy/commit/0b6f62a238c02d6f0033f225d563176fa464789e

**Comment by anteriovieira** [comment]
Hi @ais-one , it is related.  See also this https://github.com/buefy/buefy/issues/712
