### ISSUE TITLE
Typescript type definition for buefy properties

### ISSUE THREAD

**Issue by arnaudgibert** [buefy/nuxt-buefy#42]
Hi!

nuxt-buefy version: 0.3.7
nuxt version: 2.6.3
OS/Browser: Windows
Description

As described here:
https://github.com/buefy/buefy/issues/701
type where added on buefy v0.6.4 but not yet in nuxt-buefy

Wich mean that I cannot do my tsc without a dirty workaround and that I don't I have the auto-completion wich exist since it has been added on 0.6.4

It would be nice to have them ;) Thanks!

**Comment by jtommy** [comment]
What workaround are you using?

**Comment by arnaudgibert** [comment]
I create a class wich extends Vue from 'vue-property-decorator' wich include the different properties of buefy like "$toast"
Then I use this class in my script in .vue files... Very dirty, very unsafe, and very problematic for the futur but I hope this is only temporary. ^^

**Comment by jtommy** [comment]
Should you not able to use the types of Buefy package?

**Comment by arnaudgibert** [comment]
Nop beacause the types from package adds to 'vue' and I use vue from vue-property-decorator when I use typescript which I stoped doing because of the complexity of using it in my express / node server + nuxt.


________________________________

**Comment by jtommy** [comment]
@arnaudgibert Could you check last version ?

**Comment by gluons** [comment]
Try adding `buefy/types` to `compilerOptions.types` in your **tsconfig.json**.  
It shoud solve your problem.

```diff
{
	"compilerOptions": {
+		"types": ["buefy/types"]
	}
}
```
