### ISSUE TITLE
How do you customize buefy with this module?

### ISSUE THREAD

**Issue by zacharyw** [buefy/nuxt-buefy#43]
Here are the official Buefy docs on customization: https://buefy.org/documentation/customization

But I haven't been able to figure out how to get it working when using the nuxt-buefy module.

**Comment by thebspin** [comment]
Did you find out yet? Still trying to figure it out myself

**Comment by zacharyw** [comment]
@thebspin I have not, was hoping a maintainer of this library had some insight.

**Comment by jtommy** [comment]
Did you add the scss file into nuxt.config.js?
For example: 
Like nuxt documentation I've done :
css: [
    '@/assets/css/main.scss'
  ],

**Comment by thebspin** [comment]
This is what ended up working for me:

```
// Set your colors
$primary: #674ea7;
$link: #ff9900;
$footer-background-color: #2c2f34;
$link-hover: $primary;

@import "~bulma";
@import "~buefy/src/scss/buefy";
```

Note that @import "~bulma/sass/utilities/_all"; on top WOULD NOT work like the documentation says. And yes i import the scss in nuxt.config.js

This approach also gives me issue's with a lot of duplicate css. If i want to access the primary color in a component that is scoped just like vue tells me to, then i have to import this scss file and by that i also import all of bulma and buefy again leaving me with a lot of duplicate css...

**Comment by colynb** [comment]
> Did you add the scss file into nuxt.config.js?
> For example:
> 
> ```
> css: [
>     '@/assets/scss/main.scss'
>   ],
> ```

This is still not working. I did exactly what the docs say to do. The primary color is still purple. Where is it even setting the purple color?

**Comment by benjick** [comment]
@colynb any luck?

**Comment by thebspin** [comment]
So i made a codesandbox to show what is and what isnt working...
Defining custom colors like the documentation says works...
Overriding colors like primary does not seem to work.

Link to codesandbox: https://codesandbox.io/s/bold-sun-jfio9

@jtommy please advise :)

**Comment by hmaesta** [comment]
I am facing the same problem 😐

**Comment by franzos** [comment]
1. Create a `/assets/scss/main.scss`
2. Copy the _Example_ from [buefy.org](https://buefy.org/documentation/customization)
3. Modify for ex. `$primary: #8c67ef;` to another value
4. Reference in `nuxt.config.{ts/js}` like this:

```ts
css: ["@/assets/scss/main.scss"]
```

If you need to include other css files, do:

```ts
css: ["@/assets/scss/main.scss", "~/assets/css/main.css"],
```

**Restart `nuxt` to apply config!**

**Comment by DylanHobbs** [comment]
@franzos writes truth.
If you find this isn't working, make sure you're not overly tired and didn't quite copy the entire [buefy](https://buefy.org/documentation/customization) file.

You'll need the opening and closing sections around any changes you make.
`@import "~bulma/sass/utilities/_all";
...
...
@import "~bulma";
@import "~buefy/src/scss/buefy";
`

**Comment by thebspin** [comment]
> @franzos writes truth.
> If you find this isn't working, make sure you're not overly tired and didn't quite copy the entire [buefy](https://buefy.org/documentation/customization) file.

That is exactly what i'm doing in my example: https://codesandbox.io/s/nuxt-buefy-customize-bcsod
Yet the primary color does not change...

**Comment by franzos** [comment]
@thebspin it appears to be working just fine, no?

<img width="329" alt="Screen Shot 2020-02-24 at 1 28 15 PM" src="https://user-images.githubusercontent.com/2619225/75152546-98512b80-5709-11ea-8f58-d7ccdb06bcee.png">

**Comment by thebspin** [comment]
It is red for you?

![image](https://user-images.githubusercontent.com/203133/75162812-68605300-571e-11ea-97d6-81b2015c560b.png)

Here it's the default color for me :/

**Comment by franzos** [comment]
@thebspin that's rather odd. Yes, it's red, just as posted above.

Have you tried running this locally? Maybe codesandbox.io messes up something in the background - I can't really tell since everything is fine. Alternatively, try a different browser. I tested this on ungoogled-chromium 78.0.3904.97.

**Comment by Ratatinator97** [comment]
Have you guys solved the css duplicates ?

**Comment by vcruvinelr** [comment]
Hope this can help someone as worked nice for me. I put the code below in App.vue.

**Versions:**
"vue": "^2.6.11",
"buefy": "^0.9.4",
"node-sass": "^5.0.0",
"sass-loader": "^10.1.0",

**Working code:**

```
<style lang="scss">
@import "~bulma/sass/utilities/_all";
  $primary: #2a008c;
  $primary-invert: findColorInvert($primary);
$colors: (
    "white": ($white, $black),
    "black": ($black, $white),
    "light": ($light, $light-invert),
    "dark": ($dark, $dark-invert),
    "primary": ($primary, $primary-invert),
    "info": ($info, $info-invert),
    "success": ($success, $success-invert),
    "warning": ($warning, $warning-invert),
    "danger": ($danger, $danger-invert),

);
$link: $primary;
$link-invert: $primary-invert;
$link-focus-border: $primary;

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";

</style>
```

**Comment by Aztriltus** [comment]
For those who are using tailwind with buefy, you might find that bulma is overwriting some of the spacing utilities like paddings and margins with !important tag. One way to workaround this is to exclude the import of this file. 

E.g.
```
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors here
$primary: #0085FD;
// and other colors
// End of set colors

// Import Bulma styles individually
@import "bulma/sass/base/_all";
@import "bulma/sass/elements/_all";
@import "bulma/sass/form/_all";
@import "bulma/sass/components/_all";
@import "bulma/sass/grid/_all";

// @import "bulma/sass/helpers/_all"; // Basically don't import all the helpers
@import "bulma/sass/helpers/color";
@import "bulma/sass/helpers/flexbox";
@import "bulma/sass/helpers/float";
@import "bulma/sass/helpers/other";
@import "bulma/sass/helpers/overflow";
@import "bulma/sass/helpers/position";
// @import "bulma/sass/helpers/spacing"; // And most importantly leave this out
@import "bulma/sass/helpers/typography";
@import "bulma/sass/helpers/visibility";

@import "bulma/sass/layout/_all";

// Import Buefy component css
@import "~buefy/src/scss/buefy";
```
Also with this workaround, be sure to set `css: false` in your nuxt-buefy options if you're using nuxt buefy module. 

Hope this helps somebody out there

**Comment by MarijnSt** [comment]
> > @franzos writes truth.
> > If you find this isn't working, make sure you're not overly tired and didn't quite copy the entire [buefy](https://buefy.org/documentation/customization) file.
> 
> That is exactly what i'm doing in my example: https://codesandbox.io/s/nuxt-buefy-customize-bcsod
> Yet the primary color does not change...

You still have the issue? I saw your missing this buefy option this in your nuxt.config.js:
```
buefy: {
    css: false
  },
```
Might explain why your custom styles are still overwritten by the module?

**Comment by pencilcheck** [comment]
> For those who are using tailwind with buefy, you might find that bulma is overwriting some of the spacing utilities like paddings and margins with !important tag. One way to workaround this is to exclude the import of this file.
> 
> E.g.
> 
> ```
> // Import Bulma's core
> @import "~bulma/sass/utilities/_all";
> 
> // Set your colors here
> $primary: #0085FD;
> // and other colors
> // End of set colors
> 
> // Import Bulma styles individually
> @import "bulma/sass/base/_all";
> @import "bulma/sass/elements/_all";
> @import "bulma/sass/form/_all";
> @import "bulma/sass/components/_all";
> @import "bulma/sass/grid/_all";
> 
> // @import "bulma/sass/helpers/_all"; // Basically don't import all the helpers
> @import "bulma/sass/helpers/color";
> @import "bulma/sass/helpers/flexbox";
> @import "bulma/sass/helpers/float";
> @import "bulma/sass/helpers/other";
> @import "bulma/sass/helpers/overflow";
> @import "bulma/sass/helpers/position";
> // @import "bulma/sass/helpers/spacing"; // And most importantly leave this out
> @import "bulma/sass/helpers/typography";
> @import "bulma/sass/helpers/visibility";
> 
> @import "bulma/sass/layout/_all";
> 
> // Import Buefy component css
> @import "~buefy/src/scss/buefy";
> ```
> 
> Also with this workaround, be sure to set `css: false` in your nuxt-buefy options if you're using nuxt buefy module.
> 
> Hope this helps somebody out there

For those visiting this thread, find previous answers not working, here is my working scss.

```
$primary: #c32929;
$info: #002040;
$link: #c32929; // changes tabs active item

// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Import bulma styles
//@import "~bulma";

// Import Bulma styles individually
@import "~bulma/sass/base/_all";
@import "~bulma/sass/elements/_all";
@import "~bulma/sass/form/_all";
@import "~bulma/sass/components/_all";
@import "~bulma/sass/grid/_all";

// @import "~bulma/sass/helpers/_all"; // Basically don't import all the helpers
@import "~bulma/sass/helpers/color";
@import "~bulma/sass/helpers/flexbox";
@import "~bulma/sass/helpers/float";
@import "~bulma/sass/helpers/other";
@import "~bulma/sass/helpers/overflow";
@import "~bulma/sass/helpers/position";
// @import "~bulma/sass/helpers/spacing"; // And most importantly leave this out
@import "~bulma/sass/helpers/typography";
@import "~bulma/sass/helpers/visibility";

@import "~bulma/sass/layout/_all";

// Import buefy styles
@import "~buefy/src/scss/buefy";
```

Make sure you move your variable to the top of the file, before importing anything then it will work.
