### ISSUE TITLE
Setting css: false for nuxt-buefy options breaking toast, snackbar dialogs and possibly others.

### ISSUE THREAD

**Issue by cdrandin** [buefy/nuxt-buefy#47]
I have the following versions:

```json
"vue": "^2.5.17"
"nuxt": "^2.8.0"
"nuxt-buefy": "^0.3.15"
```

When I do the following in `nuxt.config.js` in modules

```js
[...],
[
    "nuxt-buefy",
    {
        css: false
    },
],
```

for some reason, I can no longer trigger toast, snackbar nor dialogues. 

this is just something I came across and I am unsure if this is a bug or intentional.

**Comment by jtommy** [comment]
What version did you use before?

**Comment by cdrandin** [comment]
I was using `"nuxt-buefy": "^0.3.6"` prior, but had since upgraded.

**Comment by jtommy** [comment]
There are some breaking change, please check Buefy release 0.8.0 https://github.com/buefy/buefy/blob/dev/CHANGELOG.md#080
