### ISSUE TITLE
How to remove material design cdn

### ISSUE THREAD

**Issue by Letty** [buefy/nuxt-buefy#48]
Hello,

nuxt: 2.6.3
nuxt-buefy: 0.3.13

Is there an option to remove the CDN for material design icons and use a package instead? Similar to this https://github.com/buefy/buefy/issues/1500

A workaround would would be: 
having everything from https://github.com/Templarian/MaterialDesign-Webfont in the assets. Include the mdi css in the global css options and remove the link to the CDN

```
css: [
	'@/assets/mdi/css/materialdesignicons.min.css'
],
buefy: {
	materialDesignIcons: true,
	materialDesignIconsHRef: '/'
},
```

I have it like this right now. But this is more like a hack then a proper method to keep my projects free from third party cdn's.

Thank you!

**Comment by jtommy** [comment]
To remove mdi loading from CDN you have to set to false the variable materialDesignIcons and you are free to import the font icon pack as you want

**Comment by fullstackdev-online** [comment]
it's a bit unclear where the variable materialDesignIcons should be set to false, so far in my nuxt.config.js in the vuetify module I've put 
```
defaultAssets: undefined
```
which can be anything but 'object', then the loader doesn't trigger the setupIcons and setupFont functions which push the cdn links to the header.

**Comment by joaom182** [comment]
Create a folder on path `/assets/mdi` and put all the mdi assets.

eg:
![Screen Shot 2020-12-22 at 16 12 18](https://user-images.githubusercontent.com/3612098/102924508-797a0d80-4470-11eb-878a-25daed4ebb9e.png)

On your `nuxt.config.js` add:
```
css: ['@/assets/mdi/css/materialdesignicons.min.css'],
buefy: {
    defaultIconPack: 'mdi',
    materialDesignIcons: false,
    materialDesignIconsHRef: '/'
},
```

**Comment by anjoseb121** [comment]
You can install it with `npm`

```
npm install --save @mdi/font
```

add it to your `nuxt.config.js`

```
css: ["@mdi/font/css/materialdesignicons.css"]
```

Source: https://stackoverflow.com/a/61040177/6454632
