### ISSUE TITLE
How to only import the Navbar and Dropdown using this module?

### ISSUE THREAD

**Issue by slidenerd** [buefy/nuxt-buefy#55]
Apologies if this seems like a silly question
- I only want the Navbar and dropdown from Buefy
- I could not find it in #43 #17 and #28 
- The [customization documentation HERE](https://buefy.org/documentation/customization/) is modifying Bulma variables, it imports the entire Buefy SCSS file, how do i get only the navbar and dropdown from this
- Could you kindly update README.md to cover such scenarios?

**Comment by jtommy** [comment]
@slidenerd you might try to import all bulma and single components instead all buefy, for example:
```
@import "~buefy/src/scss/utils/_all";
@import "~buefy/src/scss/components/_dropdown";
```
