### ISSUE TITLE
"buefy" : "latest" in package.json

### ISSUE THREAD

**Issue by agcty** [buefy/nuxt-buefy#6]
When buefy (or bulma) get's updated this might break some things when running `npm install` the next time. Wouldn't it be better and safer to manually bump the buefy version for each release?

**Comment by anteriovieira** [comment]
Hi @agcty, i agree with you. A pull request is welcome. :smiley:

**Comment by damien-biasotto** [comment]
@anteriovieira I think you might be able to close this one .

**Comment by anteriovieira** [comment]
Thanks @damien-biasotto

**Comment by justinshea** [comment]
Do the maintainers plan to update nuxt-buefy sometime soon? Buefy has released added a ton of components since October, 2018. Is there a safe way for users of nuxt-buefy to update buefy on their own?
Cheers.

**Comment by jtommy** [comment]
I don't understand, I made a new release yesterday
