### ISSUE TITLE
VSCode Intellisense does not show tags or hints

### ISSUE THREAD

**Issue by rohaanhamid** [buefy/nuxt-buefy#60]
I tried creating a new project with @Vui/CLI with Buefy and my setup works.

I have also tried installing the buefy-helper-json package. How can this be fixed?

**Comment by jtommy** [comment]
You haven't install buefy-helper because vetur reads it automatically

**Comment by rohaanhamid** [comment]
Just an FYI, I manually copied the tags.json and attributes.json files from Buefy and added them Nuxt-Buefy along with the Vetur setting in package.json and all the tags now work. I think there a PR to do do this automatically.

**Comment by jtommy** [comment]
No, there is already a PR on vetur repository that allows to read the .json from buefy bundle. Thanks anyway

**Comment by rohaanhamid** [comment]
Alright that makes sense.
