### ISSUE TITLE
Toast not working from 0.3.0

### ISSUE THREAD

**Issue by claide** [buefy/nuxt-buefy#61]
Hi, been using this package for a year now but I wonder why toasts are not working anymore. Already did upgraded to v0.3.30 but still no luck.

**package.json**
`"nuxt-buefy": "^0.3.30",`

**nuxt.config.js**
```
...
modules: [
    ...
    'nuxt-material-design-icons',
    ['nuxt-buefy', { css: false, materialDesignIcons: true }]
    ...
  ],
...
```

**component**
```
mounted() {
    this.$buefy.toast.open('Something happened')
},
```

**Comment by astagi** [comment]
Hi @claide 

I tried your code using nuxt-buefy v0.3.30 both in universal mode and static generation, everything works fine for me

![image](https://user-images.githubusercontent.com/537363/82731338-60f11b80-9d06-11ea-8afb-4a7169385a27.png)

Could you please share your project?

**Comment by claide** [comment]
Hey, thanks for your response. It's working now maybe some other packages causes the issue. Thanks again.
