### ISSUE TITLE
Mobile Responsiveness Issue

### ISSUE THREAD

**Issue by Kimeiga** [buefy/nuxt-buefy#62]
The following screenshots are from a new app from the `yarn create nuxt-app hello-world` command with buefy selected as the framework of choice.

![image](https://user-images.githubusercontent.com/20587215/82539558-7c8bd480-9b02-11ea-9a53-8720ec9cb231.png)

Looks fine on desktop

![image](https://user-images.githubusercontent.com/20587215/82539626-96c5b280-9b02-11ea-87b4-418b76380f2d.png)

Problem with body width and card overflow on mobile. Maybe incorrect responsive breakpoints?

**Comment by Kimeiga** [comment]
I actually also had to change the icon from `github-circle` to `github` for it to show

**Comment by Kimeiga** [comment]
Oh guys i think its because the 4 cards aren't looping to the next column in this example screen

**Comment by Kimeiga** [comment]
Ok sorry for the spam, when I removed `is-mobile` from the `<div class="columns">` of index.vue of pages, it fixed the issue by stacking the cards. I guess it would be nice to update the default nuxt-buefy template to this for better mobile experience but it is up to your discretion

**Comment by jtommy** [comment]
It's on old template I should update it

**Comment by Kimeiga** [comment]
ty bro
