### ISSUE TITLE
Vertical steps doesn't seem to work

### ISSUE THREAD

**Issue by miketeix** [buefy/nuxt-buefy#63]
Hi there, for some reason, vertical steps aren't working, was wondering if anyone else has faced this issue....

**Comment by jtommy** [comment]
What do you mean?

**Comment by miketeix** [comment]
Sry, I just updated `nuxt-buefy` to latest and they seems to work now.
I'm guessing vertical version of the steps component only arrived in a recent version of buefy, so the upgrade did the trick.
THanks!
