### ISSUE TITLE
Easy way to get the latest Buefy

### ISSUE THREAD

**Issue by miketeix** [buefy/nuxt-buefy#71]
Hi there, is there an easy way to get the latest Buefy without doing a PR to to this repo?
Currently Buefy is at 0.9.1 I believe.

Cheers!

**Comment by jtommy** [comment]
Sure, update nuxt-buefy to 0.4.1

**Comment by miketeix** [comment]
Thanks! Yeah I just looking in the Tags and Releases section, should have checked the package.json as well. Cheers!
