### ISSUE TITLE
HTMLImageElement is not defined

### ISSUE THREAD

**Issue by toddheslin** [buefy/nuxt-buefy#72]
Using the new `<b-image>` component throws an error: https://buefy.org/documentation/image

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/1883112/91235485-bd425c00-e789-11ea-8b5c-34785324f8c1.png">

**Comment by cezardasilva** [comment]
Hi @toddheslin. You can try this:

Put this line of code at the begging of you nuxt.config.js
`global.HTMLImageElement =
  typeof window === 'undefined' ? Object : window.HTMLImageElement`

That worked for me

**Comment by jtommy** [comment]
Will fix soon!

**Comment by quirkles** [comment]
+1 on this issue

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/pull/2866
