### ISSUE TITLE
b-table slot-scope="props"  empty

### ISSUE THREAD

**Issue by OnDreBug** [buefy/nuxt-buefy#77]
Version: 0.4.3

I changed from Version `"nuxt-buefy": "^0.3.31",` to 0.4.3 and now the props is empty and i get the error: "Cannot read property 'id' of undefined"

 <b-table v-if="data" :data="data">
        <template slot-scope="props">
          <b-table-column field="id" label="Id" width="40">
            {{ props.row.id }}
          </b-table-column>
       </template>
</b-table>

<script>
    export default {
        data() {
            return data = [
                { 'id': 1, 'first_name': 'Jesse', 'last_name': 'Simmons', 'date': '2016/10/15 13:43:27', 'gender': 'Male' },
                { 'id': 2, 'first_name': 'John', 'last_name': 'Jacobs', 'date': '2016/12/15 06:00:53', 'gender': 'Male' },
                { 'id': 3, 'first_name': 'Tina', 'last_name': 'Gilbert', 'date': '2016/04/26 06:26:28', 'gender': 'Female' },
                { 'id': 4, 'first_name': 'Clarence', 'last_name': 'Flores', 'date': '2016/04/10 10:28:46', 'gender': 'Male' },
                { 'id': 5, 'first_name': 'Anne', 'last_name': 'Lee', 'date': '2016/12/06 14:38:38', 'gender': 'Female' }
            ],
        }
    }
</script>

**Comment by jtommy** [comment]
Nee Buefy introduced breaking changes on table component, please take a look at docs
