### ISSUE TITLE
<b-image>not found

### ISSUE THREAD

**Issue by Ratatinator97** [buefy/nuxt-buefy#80]
Hey, I can't use the <b-image>, as the error below shows, it is unknown.
`[Vue warn]: Unknown custom element: <b-image> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Many thanks for your awesome work

**Comment by jtommy** [comment]
How are you importing Buefy?

**Comment by Ratatinator97** [comment]
In `nuxt.config.js` I have the following code : 
`modules: [
    // Doc: https://buefy.github.io/#/documentation
    "nuxt-buefy",
    "@nuxtjs/pwa"
  ],`

**Comment by jtommy** [comment]
What version? Probably you are not using buefy 0.9.x

**Comment by Ratatinator97** [comment]
Yeah, I have the 8.2. How can I update this ? When I run `npm update --save` it doesn't shows me newer versions of buefy... How can I do it ?

**Comment by jtommy** [comment]
You have to upgrade to last nuxt-buefy version
