### ISSUE TITLE
defaultDateParser and defaultDateFormatter functions are not being setted to datepickers components,

### ISSUE THREAD

**Issue by mrtnzagustin** [buefy/nuxt-buefy#83]
Version 0.3.3
defaultDateParser and defaultDateFormatter functions are not being setted to datepickers components, other options like defaultMonthNames are working.

![imagen](https://user-images.githubusercontent.com/12588882/97430035-0c764b80-18f7-11eb-94c2-c6ae686570ad.png)

![imagen](https://user-images.githubusercontent.com/12588882/97430810-2cf2d580-18f8-11eb-9f0f-099e1fe0201f.png)

**Comment by mrtnzagustin** [comment]
I think the problem is in https://github.com/buefy/nuxt-buefy/blob/master/lib/templates/plugin.js
Perhaps JSON.stringify does not work well with functions!!
I did my own pluging to add "buefy" to nuxt and make it work. Can you check it please? Thanks!!

Regards,
Agustin

**Comment by jtommy** [comment]
Yes, you are right. I think I'll remove it

**Comment by mrtnzagustin** [comment]
Ok, great. I'll upgrade to buefy 9 / nuxt-buef 4 then. Thank you Jeremy

**Comment by jtommy** [comment]
Jeremy??

**Comment by mrtnzagustin** [comment]
jtommy + walter + my dev brain = Jeremy, sorry !! thanks walter

**Comment by wesdevpro** [comment]
@jtommy did you ever finish this?

**Comment by jtommy** [comment]
We cannot use it with json config

**Comment by wesdevpro** [comment]
> We cannot use it with json config

In other words close this?
