### ISSUE TITLE
Add ability to pass in theme colors into config

### ISSUE THREAD

**Issue by leerobert** [buefy/nuxt-buefy#85]
It would be a nice feature upgrade to have the ability to pass in theme colors via the config aka:

```js
  modules: [
    // https://go.nuxtjs.dev/buefy
    ['nuxt-buefy', {primary: '#242424', link: '#424242', ...}]
  ]
```

I'm an absolute nuxt noob or I'd put up a PR

**Comment by jtommy** [comment]
It's no possibile because color variables are sass/scss variables
