### ISSUE TITLE
Buefy import options not working

### ISSUE THREAD

**Issue by nmaxcom** [buefy/nuxt-buefy#88]
I've tried both ways:
```js
  // Modules (https://go.nuxtjs.dev/config-modules)
  modules: [
    'nuxt-buefy',
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
  ],
  buefy:{
    css: false,
    materialDesignIcons: true,
    defaultLocale: 'es-ES',
    defaultDialogConfirmText: 'Aceptar',
    defaultDialogCancelText: 'Cancelar'
  },
```
and:
  ```js
// Modules (https://go.nuxtjs.dev/config-modules)
  modules: [
    [
      'nuxt-buefy',
      {
        css: false,
        materialDesignIcons: true,
        defaultLocale: 'es-ES',
        defaultDialogConfirmText: 'Aceptar',
        defaultDialogCancelText: 'Cancelar'
      }
    ],
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
  ],
```

In either way it stops importing the CSS and the styling breaks. I don't see any errors anywhere.

**Comment by fabiofdsantos** [comment]
Did you define `css` property in nuxt.config? E.g. `css: ['@/assets/scss/main.scss']`

You should also include in .scss file:
```scss
// Import bulma styles
@import "~bulma";

// Import buefy styles
@import "~buefy/src/scss/buefy";
```

**Comment by nmaxcom** [comment]
Thanks for helping @fabiofdsantos. I haven't tried your solution but I found a way to make it work playing with the CSS property which makes me think you are right.
However, why is this not explained in this repo's readme? I find myself too often struggling with stuff that would work from the get-go but it doesn't. Granted, I'm a newbie using nuxt/buefy, but isn't that the point of the documentation?
It's nuxt-buefy, however, there's almost no info on how to make it work in Nuxt.

**Comment by fabiofdsantos** [comment]
@nmaxcom I created a PR to make it clear in the readme 👍🏻
