### ISSUE TITLE
Customizing SCSS

### ISSUE THREAD

**Issue by erichodges** [buefy/nuxt-buefy#9]
Hi, 

Where and how do I customize the scss? I want to change the colors of primary etc., but also want to be able to change anything and everything. :-)

I know about:
`@import "~bulma/sass/utilities/_all";`
But I don't know where to put it. 
:-(

**Comment by anteriovieira** [comment]
Hi @erichodges , you can create a file in the assets folder and then import the file by placing it in the css property of `nuxt.config.js`

`assets/my-style.scss`
```scss
@import "~bulma/sass/utilities/_all";

// ...
```

`nuxt.config.js`
```js
module.exports = {
    ...
    css: [
        'assets/my-style.scss'
    ]
}
```

**Comment by erichodges** [comment]
Thanks, that works for using `assets/my-style.scss`. 

I would also like to have additional files that I import into `assets/my-style.scss`, such as `assets/_base.scss` etc. I've tried this, and moved the @import around, but it's not letting me use scss variables ($primary etc.) in the other files or in the <style> tags of .vue files. 

Is there a way that I can set this up?

**Comment by anteriovieira** [comment]
> Is there a way that I can set this up?

yes, you should use [nuxt-sass-resources-loader](https://github.com/anteriovieira/nuxt-sass-resources-loader) and point your variables file.

**Comment by erichodges** [comment]
Cool, thank you! It actually worked, lol. 

Ok, I still don't know what variable bulma is using for the purple color in the navigation menu items. Maybe you don't know...I can ask the bulma people.

**Comment by damien-biasotto** [comment]
@erichodges I don't see any purple in the bulma documentation:
https://bulma.io/documentation/components/navbar/#variables


It might be the guys from buefy and from what I'm seeing, they are also using the variable `$link` that uses the `$primary` variable which is purple.

**Comment by erichodges** [comment]
@damien-biasotto   Cool thanks, I'll see what I can do with that.

**Comment by erichodges** [comment]
@damien-biasotto  Ok, I was able to change the color of the link. On dropdown menus there's a down arrow (upside down chevron) which is still not changing. Any idea how to control that?

**Comment by damien-biasotto** [comment]
@erichodges yes you have to change the `border-color` of the dropdown in the `::after` pseudo selector (source https://github.com/jgthms/bulma/issues/545#issuecomment-284288581)

**Comment by erichodges** [comment]
@damien-biasotto Cool, thank you! I also found it (the chevron thing) in the dev tools. 

I'll look into controlling the other items. I can probably find them through the dev tools as well.

**Comment by damien-biasotto** [comment]
@erichodges Would you mind closing this issue if it's okay on your side?

**Comment by damien-biasotto** [comment]
Thank you @erichodges, happy coding :)

**Comment by angad777** [comment]
Hi @anteriovieira - nuxt.config.js seems to have changed ?

```
modules: [,

    // Doc: https://buefy.github.io/#/documentation
    'nuxt-buefy'
    '''
  ],

```

**Comment by bgalvao** [comment]
Hi, I am having this issue today, and I followed this [guide](https://hackernoon.com/how-i-use-scss-variables-mixins-functions-globally-in-nuxt-js-projects-while-compiling-css-utilit-58bb6ff30438) using `@nuxtjs/style-resources`.

This is my `nuxt.config.js`:
```
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/style-resources',
    ['nuxt-buefy', {materialDesignIcons: false}]
  ],
  styleResources: {
    scss: [
      './assets/main.scss'
    ]
  },
```

But it doesn't seem to find `./assets/main.scss`, as I did a double check and renamed the file to something different than the path specified in `nuxt.config.js` and it did not throw an error. Am I doing something wrong?

**Comment by colynb** [comment]
This is no longer working. Here is my set up:

`assets/app.scss`
```css
// Import Bulma's core
@import '~bulma/sass/utilities/_all';

// Set your colors
$primary: #48bb78; // green
...
```

`nuxt.config.js`
```
...
css: ['@/assets/app.scss'],
modules: [
    'nuxt-buefy',
],
...
```

I restarted nuxt.

The primary color remains purple.

**Comment by claide** [comment]
install [@nuxt/style-resources](https://www.npmjs.com/package/@nuxtjs/style-resources)

**nuxt.config.js**

```
css: [
    '@/assets/your-style.scss'
],
modules: [
   'nuxt-buefy',
   '@nuxtjs/style-resources',
   ...
]
```

**your-style.scss**
```
@import "~bulma/sass/utilities/_all";

// variables
$table-color: #212529;
$table-background-color: $dark-mild;
...

@import "~bulma";
@import "~buefy/src/scss/buefy";
```

**Comment by donmb1** [comment]
I am having hard times with this, tried the solutions above

`assets/main.sass`
```
@import "~bulma/sass/utilities/_all"

$primary: #000000 !default

@import "~bulma"
@import "~buefy/src/scss/buefy"
```

`nuxt.config.js`
```
  css: [
    './assets/main.sass'
  ],
```

but my primary color still appears default `$turquoise`
I just cannot overwrite it. What do I do wrong?

**Comment by jtommy** [comment]
@donmb1 you have to remove `!default`

**Comment by donmb1** [comment]
@jtommy that does not change it either
but this solution works for me:

```
$turquoise: #000
$primary: #000000
$secondary: #000000

@import "~bulma/sass/utilities/_all"
@import "~bulma"
@import "~buefy/src/scss/buefy"
```

I had to put `@import "~bulma/sass/utilities/_all"` underneath the variable declaration
https://github.com/buefy/buefy/issues/319#issuecomment-427642851

**Comment by jcorry** [comment]
I had to install `sass` and `sass-loader` for this to work:

`yarn add node-sass sass-loader -D`

**Comment by jmc529** [comment]
You do not actually need "@import "~bulma/sass/utilities/_all"" as it comes with bulma

**Comment by charles-salmon** [comment]
If you're using `nuxt-buefy` and `@nuxtjs/style-resources`, I found that the following approach worked quite nicely for me:

**~/nuxt.config.js:**
```javascript
...

export default {
...

  buildModules: [
    ...
    '@nuxtjs/style-resources',
  ],

  modules: [
    ...
    ['nuxt-buefy', { css: false }],
  ],

  styleResources: {
    ...
    scss: [
      '~/assets/css/utilities.scss',
    ],
  },
  
  css: [
    ...
    '~/assets/css/main.scss',
  ],

...
}
```

**~/assets/css/utilities.scss:**
```scss
@import "~bulma/sass/utilities/functions";
@import "~bulma/sass/utilities/initial-variables";
@import "~buefy/src/scss/utils/_all";

// If you override or set variables here, they will be available available to you from within your Vue components, without requiring @import statements.
```

**~/assets/css/main.scss:**
```scss
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
