### ISSUE TITLE
Is nuxt-buefy is also has the latest component as the buefy component library?

### ISSUE THREAD

**Issue by BroJenuel** [buefy/nuxt-buefy#94]
I was wondering because when I look at the releases in nuxt-buefy, the release is in 2018. Sorry, I just would like to ask, because no discussion tab.

![image](https://user-images.githubusercontent.com/31676163/111419909-38b72b00-8725-11eb-840b-4f5f6ea4f787.png)

**Comment by jtommy** [comment]
Because I always forget to update it 😛.
I'll update with next version
