### ISSUE TITLE
annoying scrollbar on the right-side browser.

### ISSUE THREAD

**Issue by AnasR7** [buefy/nuxt-buefy#95]
after the new installation with nuxt-buefy, I got something bugging me
there is a scrollbar on the right-side browser.

![2021-03-25_13:03](https://user-images.githubusercontent.com/23519166/112428098-367c4e80-8d6d-11eb-996d-55ec95b36731.png)

I'm using firefox and I think is overflow-x section problem and I add overflow-x: hidden code into my CSS body{}, apparently not, instead, it got messed up and a scrollbar appeared, sorry I am still a newbie in frontend dev.

this my version of nuxt-buefy :
![2021-03-25_13:14](https://user-images.githubusercontent.com/23519166/112428257-79d6bd00-8d6d-11eb-9013-060b8335a23f.png)

maybe is my error or it is just a new bug thanks.

**Comment by jtommy** [comment]
I don't know to be honest but anyway it's only a sample template (probably old and to change/improve)

**Comment by GMartigny** [comment]
Bulma is setting the [`html` tag as `overflow: scroll`](https://github.com/jgthms/bulma/blob/master/sass/base/generic.sass#L9) by default.
