### ISSUE TITLE
A way to specify which JS components to include

### ISSUE THREAD

**Issue by stieben** [buefy/nuxt-buefy#98]
I have a minimal Nuxt site; my _main.scss_ only loads the following Buefy files:

```scss
@import '~buefy/src/scss/utils/_all';
@import '~buefy/src/scss/components/_message';
```

Which is to say: Choosing what SCSS to include works. ✔️

Regarding the JS part of the components – Buefy supports including specific components:

```javascript
import { Input, Table } from 'buefy'

Vue.use(Input)
Vue.use(Table)
```

Is there a way to do the same with `nuxt-buefy`? As I understand, `nuxt-buefy` automatically imports all components, so my _vendors_ chunk looks like this:

![Webpack Bundle Analyzer](https://imghostr.com/image.php?sig=8M2M5ycS&h=af14e46155a083b36c0d00e9500e4fc2&t=1619364640)

**Comment by jtommy** [comment]
No you have to create a your own plugin
